// Games for an upcoming round to use for picks
export const games = [
  {
    id: '123',
    teamA: {
      name: 'Arizona',
      abbreviation: 'RMD',
      isAway: true,
      isHome: false,
      teamId: '123A',
      ranking: 10,
      normalizedId: 192,
      score: 60,
      isWinner: false,
      record: '13-9',
      logo: 'https://dbukjj6eu5tsf.cloudfront.net/sidearm.sites/arizona.sidearmsports.com/images/logos/site/site.png',
    },
    teamB: {
      name: 'Duke',
      abbreviation: 'RMD',
      isAway: true,
      isHome: false,
      teamId: '123B',
      ranking: 10,
      normalizedId: 192,
      score: 60,
      isWinner: false,
      record: '13-9',
      logo: 'https://sportslogohistory.com/wp-content/uploads/2018/01/duke_blue_devils_1978-pres-s.png',
    },
    eventDate: '2022-11-24T10:48:43.151Z',
    attendance: 23455,
    seasonType: 'New season',
    seasonYear: '2022',
    weekName: 'Quoter finals',
    week: 5,
    headline: 'Headline',
    gameClock: '12:00',
    locationName: 'No where',
  },
  {
    id: '456',
    teamA: {
      name: 'Arkansas',
      abbreviation: 'RMD',
      isAway: true,
      isHome: false,
      teamId: '456A',
      ranking: 10,
      normalizedId: 192,
      score: 60,
      isWinner: false,
      record: '13-9',
      logo: 'https://sportslogohistory.com/wp-content/uploads/2018/09/arkansas_razorbacks_2014-pres.png',
    },
    teamB: {
      name: 'Baylor',
      abbreviation: 'RMD',
      isAway: true,
      isHome: false,
      teamId: '456B',
      ranking: 10,
      normalizedId: 192,
      score: 60,
      isWinner: false,
      record: '13-9',
      logo: 'http://baylorbears.com/images/logos/site/site.png',
    },
    eventDate: '2022-11-24T10:48:43.151Z',
    attendance: 23455,
    seasonType: 'New season',
    seasonYear: '2022',
    weekName: 'Quoter finals',
    week: 5,
    headline: 'Headline',
    gameClock: '12:00',
    locationName: 'No where',
  },
  {
    id: '789',
    teamA: {
      name: 'Buffalo',
      abbreviation: 'RMD',
      isAway: true,
      isHome: false,
      teamId: '789A',
      ranking: 10,
      normalizedId: 192,
      score: 60,
      isWinner: false,
      record: '13-9',
      logo: 'https://ubbulls.com/images/logos/site_logo.png',
    },
    teamB: {
      name: 'Davidson',
      abbreviation: 'RMD',
      isAway: true,
      isHome: false,
      teamId: '789B',
      ranking: 10,
      normalizedId: 192,
      score: 60,
      isWinner: false,
      record: '13-9',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Davidson_Wildcats_logo.svg/1200px-Davidson_Wildcats_logo.svg.png',
    },
    eventDate: '2022-11-24T10:48:43.151Z',
    attendance: 23455,
    seasonType: 'New season',
    seasonYear: '2022',
    weekName: 'Quoter finals',
    week: 5,
    headline: 'Headline',
    gameClock: '12:00',
    locationName: 'No where',
  },
  {
    id: '012',
    teamA: {
      name: 'Bonaventure',
      abbreviation: 'RMD',
      isAway: true,
      isHome: false,
      teamId: '012A',
      ranking: 10,
      normalizedId: 192,
      score: 60,
      isWinner: false,
      record: '13-9',
      logo: 'https://s3-us-west-2.amazonaws.com/theathletic-team-logos/team-logo-326-300x300.png',
    },
    teamB: {
      name: 'Colorado',
      abbreviation: 'RMD',
      isAway: true,
      isHome: false,
      teamId: '012B',
      ranking: 10,
      normalizedId: 192,
      score: 60,
      isWinner: false,
      record: '13-9',
      logo: 'http://cubuffs.com/images/logos/site/site.png',
    },
    eventDate: '2022-11-24T10:48:43.151Z',
    attendance: 23455,
    seasonType: 'New season',
    seasonYear: '2022',
    weekName: 'Quoter finals',
    week: 5,
    headline: 'Headline',
    gameClock: '12:00',
    locationName: 'No where',
  },
];
